language: node_js
node_js:
  - node

services:
  - postgresql

jobs:
  include:
    - stage: test
      name: Unit testing
      script: npm test
    - stage: test
      name: Linting
      script: npm run lint